Initial Support for Windows Based Docker Images
game-ci/docker pull request #134
Opened 2021-12-18 00:41 UTC by AndrewKahr

#### Changes

- Added dockerfiles for windows-based containers
- Added workflow files to build windows-based base, hub, and editor images, mirroring the existing system in place for ubuntu based images
- Modified pull-request workflow file to also test windows images

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)

2021-12-18 03:07 UTC, webbertakken requested changes
Amazing work! ❤

Looking good for the most part, a things still need changing to get it into a mergeable state.

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/new-windows-base-image-requested.yml
> +    types: [new_base_image_requested, new_windows_base_image_requested]
```suggestion
    types: [new_windows_base_image_requested]
```

This is the legacy ubuntu trigger.

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/new-windows-hub-image-requested.yml
> +    types: [ new_hub_image_requested, new_windows_hub_image_requested ]
```suggestion
    types: [ new_windows_hub_image_requested ]
```

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/new-windows-hub-image-requested.yml
> +          friendlyTag: ${{ github.event.client_payload.repoVersionMinor }}
The friendly tag must match the specific tag in this case: we do not build without `windows-` prefix

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/new-windows-post-2019-2-editor-image-requested.yml
> +          friendlyTag: ${{ github.event.client_payload.repoVersionMinor }}
The friendly tag must match the specific tag in this case: we do not build without `windows-` prefix

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/new-windows-post-2019-2-editor-image-requested.yml
> +    types: [ new_2019_3_plus_editor_image_requested, new_windows_post_2019_2_editor_image_requested ]
We have to find out whether we need pre 2019.3 builds or not.

IL2CPP for windows was introduced with 2019.3, so does that mean there's no point in building any images from before 2019.3? Or is there still some use for XBox or UWP or other platforms.

Perhaps @GabLeRoux you could also pitch in here.

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/new-windows-base-image-requested.yml
> +          friendlyTag: ${{ github.event.client_payload.repoVersionMinor }}
The friendly tag must match the specific tag in this case: we do not build without windows- prefix

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/new-windows-post-2019-2-editor-image-requested.yml
> +      # TODO: Determine what we can free on windows
This will be needed for the workflow to be successful, because it'll need the files on the host system + the built result and in practice that means we'll hit the limit on some builds.

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/new-windows-post-2019-2-editor-image-requested.yml
> +          }
Can you confirm that this does indeed exit? It's a crucial step of the workflow, that prevents corruption.

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/pull-requests.yml
> +          - windows-il2cpp
Ideally we would include XBox and other target platforms that are not available on ubuntu in this iteration - but only if it's not adding too much extra effort.

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/pull-requests.yml
> +
Duplicate newline

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/pull-requests.yml
> +      # TODO: Determine what we can free on windows
Same as before

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/pull-requests.yml
> +                --build-arg changeSet=fa717bb873ec
Should use args that are provided by versioning backend, like in ubuntu workflows.

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/retry-windows-editor-image-requested.yml
> +    types: [ retry_editor_image_requested, retry_windows_editor_image_requested ]
```suggestion
    types: [ retry_windows_editor_image_requested ]
```

2021-12-18 03:07 UTC, webbertakken commented on .github/workflows/retry-windows-editor-image-requested.yml
> +          friendlyTag: ${{ github.event.client_payload.repoVersionMinor }}
same comment as before

2021-12-18 03:07 UTC, webbertakken commented on images/windows/base/100-characters-dockerhub-description.txt
> +Base image used to produce windows-based hub and editor images.
We do not need this file in windows side. Feel free to delete.

It should become a global thing at some point but out of scope.

2021-12-18 03:07 UTC, webbertakken commented on images/windows/base/Dockerfile
> +RUN powershell -Command Set-ExecutionPolicy unrestricted
missing newline at the end of the file.

Recommend installing Editorconfig plugin in your IDE, which will automatically inject these for you.

2021-12-18 03:07 UTC, webbertakken commented on images/windows/editor/100-characters-dockerhub-description.txt
> +Dockerised windows-based Unity Editor.
can be removed

2021-12-18 03:07 UTC, webbertakken commented on images/windows/editor/Dockerfile
> +
module should be passed in through the workflow (matrix in new_build flow or retry args in retry flow)

2021-12-18 03:07 UTC, webbertakken commented on images/windows/hub/100-characters-dockerhub-description.txt
> +Dockerised windows-based Unity Hub.
can be removed

2021-12-18 04:18 UTC, AndrewKahr commented on .github/workflows/new-windows-post-2019-2-editor-image-requested.yml
> +          }
I've tested it locally, and it does indeed exit with the error code 1 which should trigger github actions to see an error and exit. Is this the behavior that is needed and does this need testing on a github run?

2021-12-18 04:20 UTC, AndrewKahr commented on .github/workflows/new-windows-post-2019-2-editor-image-requested.yml
> +      # TODO: Determine what we can free on windows
Can you elaborate on what it means to need the files on the host system + the built result?

2021-12-18 04:25 UTC, AndrewKahr commented on .github/workflows/pull-requests.yml
> +                --build-arg changeSet=fa717bb873ec
This is part of the PR workflow, I'm not sure the versioning backend has a say in this though maybe I am mistaken on how this is triggered. Also the Ubuntu one hardcodes the version and changeSet in the same way. Should these both use versioning backend args?

2021-12-18 04:38 UTC, AndrewKahr commented on .github/workflows/pull-requests.yml
> +          - windows-il2cpp
https://support.unity.com/hc/en-us/articles/115005327866-How-do-I-develop-to-Xbox-platforms-
It doesn't appear that we will be able to support Xbox due to licensing. I can take a look into whether we can add in UWP support though

2021-12-18 07:01 UTC, AndrewKahr commented on .github/workflows/pull-requests.yml
> +          - windows-il2cpp
Looking at UWP, it requires an additional VS module for UWP build support, the GitHub runners already have it installed, not sure if anything is needed on the docker side to make it work (ie reg keys to point to the module). I think this is out of scope for this initial iteration which is mainly focused on il2cpp, however, it shouldn't be too difficult to add support for it down the line with the structure that is in place.

2021-12-21 11:51 UTC, webbertakken commented on .github/workflows/pull-requests.yml
> +                --build-arg changeSet=fa717bb873ec
No, you're right this part is supposed to be hardcoded.

2021-12-21 11:51 UTC, webbertakken approved these changes

2021-12-21 11:52 UTC, merged