Add support of python 2 command in android and ios
game-ci/docker pull request #152
Opened 2022-02-03 08:16 UTC by dharmeshmp

#### Changes

- Added python 2 command support to android and ios

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)

2022-02-03 08:53 UTC, webbertakken commented
When you say python2, do you mean python3?

2022-02-03 09:04 UTC, dharmeshmp commented
I have implemented second suggestion.
https://github.com/game-ci/docker/issues/100#issuecomment-1023476647

2022-02-03 09:25 UTC, webbertakken commented
> I have implemented second suggestion. [#100 (comment)](https://github.com/game-ci/docker/issues/100#issuecomment-1023476647)

Much appreciated!

Would you mind updating the PR title and comments in the code to reflect the correct version please?

2022-02-03 09:54 UTC, dharmeshmp commented
of course you can do any thing.

2022-02-03 10:40 UTC, webbertakken requested changes

2022-02-03 10:40 UTC, webbertakken commented on images/ubuntu/editor/Dockerfile
> +# [android, ios] python 2 command support
```suggestion
# [android, ios] python 3 support
```

2022-02-03 10:42 UTC, webbertakken commented
> of course you can do any thing.

Done.

Did you build the image and check if it solves your problem?

2022-02-03 11:10 UTC, dharmeshmp commented
> Did you build the image and check if it solves your problem?

No, But I checked by adding `ln -s /usr/bin/python3 /usr/bin/python` in before_script stage of gitlab.

2022-02-03 12:34 UTC, webbertakken commented
> > Did you build the image and check if it solves your problem?
> 
> No, But I checked by adding `ln -s /usr/bin/python3 /usr/bin/python` in before_script stage of gitlab.

Ok good enough. Can you confirm that that worked?

2022-02-03 13:47 UTC, dharmeshmp commented
> Ok good enough. Can you confirm that that worked?

Yes, It's working fine for me.

2022-02-03 18:41 UTC, merged

2022-02-20 07:57 UTC, mastef commented
Hi, @dharmeshmp @webbertakken 

this PR was based on my comment. After further review I would have recommended to just run the previous step for all targets :
<img width="879" alt="image" src="https://user-images.githubusercontent.com/762297/154833696-4ab75981-572b-4d58-be46-79a6e01a5f1c.png">

```diff
-RUN echo "$module" | grep -q -v '\(webgl\|linux-il2cpp\)' \
-  && exit 0 \
-  || : \
-  && apt-get -q update \
+RUN apt-get -q update \
  && apt-get -q install -y --no-install-recommends --allow-downgrades \
    python \
    python-setuptools \
    build-essential \
    clang \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
```
As that already installs `python`. It would also remove additional complexity.

2022-02-20 07:59 UTC, mastef commented
Or something like 

```diff
+RUN apt-get -q install -y python
 RUN echo "$module" | grep -q -v '\(webgl\|linux-il2cpp\)' \
   && exit 0 \
   || : \
   && apt-get -q update \
   && apt-get -q install -y --no-install-recommends --allow-downgrades \
-    python \
     python-setuptools \
     build-essential \
     clang \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/*
```

2022-02-20 08:00 UTC, mastef commented
( There's nothing wrong with the current implementation, I just noticed that python is being installed in a previous step. And for some reason I need it now also for `win/mac/unix` installs as Firebase is not filtering them in the latest version. So having `python` in all containers may be the fastest fix )